In [1]:
import pandas as pd

user_df = pd.read_csv("feature_data/user_df.csv")
display(user_df)

,UserId,total_orders,avg_order_value,total_spend,order_value_std,first_order_date,last_order_date,fav_platform,fav_city,n_platforms_used,n_cities_ordered_from,recency_days,customer_lifespan_days,avg_days_between_orders
0,7226,5,1332.600000,6663.00,590.077368,2024-09-10 19:53:14.763,2025-10-11 16:39:20.717,ios,3,2,1,172,395,79.000000
1,7397,1,320.000000,320.00,0.000000,2026-02-24 19:06:45.527,2026-02-24 19:06:45.527,web,1,1,1,36,0,0.000000
2,9802,42,1406.044048,59053.85,636.702285,2024-12-24 09:06:21.120,2026-01-19 07:53:59.733,ios,1,1,1,72,390,9.285714
3,10817,1,599.000000,599.00,0.000000,2024-06-22 17:16:12.330,2024-06-22 17:16:12.330,android,1,1,1,648,0,0.000000
4,14885,27,3866.311111,104390.40,1723.575350,2024-04-13 14:20:53.883,2026-03-19 00:56:55.993,android,1,1,1,13,704,26.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256911,1098287232065,1,500.000000,500.00,0.000000,2026-03-31 22:26:31.887,2026-03-31 22:26:31.887,ios,5,1,1,1,0,0.000000
256912,1098297712010,1,230.000000,230.00,0.000000,2026-03-31 22:35:59.940,2026-03-31 22:35:59.940,ios,1,1,1,1,0,0.000000
256913,1098306096002,1,499.000000,499.00,0.000000,2026-03-31 22:44:45.557,2026-03-31 22:44:45.557,ios,2,1,1,1,0,0.000000
256914,1098324960101,1,1560.000000,1560.00,0.000000,2026-03-31 22:50:58.427,2026-03-31 22:50:58.427,android,1,1,1,1,0,0.000000
256915,1098348016442,1,420.000000,420.00,0.000000,2026-03-31 23:17:05.110,2026-03-31 23:17:05.110,android,2,1,1,1,0,0.000000

In [2]:
user_df["order_value_std"] = user_df["order_value_std"].fillna(0)
display(user_df)

,UserId,total_orders,avg_order_value,total_spend,order_value_std,first_order_date,last_order_date,fav_platform,fav_city,n_platforms_used,n_cities_ordered_from,recency_days,customer_lifespan_days,avg_days_between_orders
0,7226,5,1332.600000,6663.00,590.077368,2024-09-10 19:53:14.763,2025-10-11 16:39:20.717,ios,3,2,1,172,395,79.000000
1,7397,1,320.000000,320.00,0.000000,2026-02-24 19:06:45.527,2026-02-24 19:06:45.527,web,1,1,1,36,0,0.000000
2,9802,42,1406.044048,59053.85,636.702285,2024-12-24 09:06:21.120,2026-01-19 07:53:59.733,ios,1,1,1,72,390,9.285714
3,10817,1,599.000000,599.00,0.000000,2024-06-22 17:16:12.330,2024-06-22 17:16:12.330,android,1,1,1,648,0,0.000000
4,14885,27,3866.311111,104390.40,1723.575350,2024-04-13 14:20:53.883,2026-03-19 00:56:55.993,android,1,1,1,13,704,26.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256911,1098287232065,1,500.000000,500.00,0.000000,2026-03-31 22:26:31.887,2026-03-31 22:26:31.887,ios,5,1,1,1,0,0.000000
256912,1098297712010,1,230.000000,230.00,0.000000,2026-03-31 22:35:59.940,2026-03-31 22:35:59.940,ios,1,1,1,1,0,0.000000
256913,1098306096002,1,499.000000,499.00,0.000000,2026-03-31 22:44:45.557,2026-03-31 22:44:45.557,ios,2,1,1,1,0,0.000000
256914,1098324960101,1,1560.000000,1560.00,0.000000,2026-03-31 22:50:58.427,2026-03-31 22:50:58.427,android,1,1,1,1,0,0.000000
256915,1098348016442,1,420.000000,420.00,0.000000,2026-03-31 23:17:05.110,2026-03-31 23:17:05.110,android,2,1,1,1,0,0.000000

In [3]:
user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 256916 entries, 0 to 256915
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   UserId                   256916 non-null  int64
 1   total_orders             256916 non-null  int64
 2   avg_order_value          256916 non-null  float64
 3   total_spend              256916 non-null  float64
 4   order_value_std          256916 non-null  float64
 5   first_order_date         256916 non-null  str
 6   last_order_date          256916 non-null  str
 7   fav_platform             256916 non-null  str
 8   fav_city                 256916 non-null  int64
 9   n_platforms_used         256916 non-null  int64
 10  n_cities_ordered_from    256916 non-null  int64
 11  recency_days             256916 non-null  int64
 12  customer_lifespan_days   256916 non-null  int64
 13  avg_days_between_orders  256916 non-null  float64
dtypes: float64(4), int64(7), str(3)
memory usage: 39.9 MB

In [4]:
df_order_level = pd.read_csv("feature_data/df_order_level.csv")
display(df_order_level)

,OrderId,UserId,VendorId,CreatedDate,OrderType,OrderSubTotal,Platform,CityID,OrderSubTotal_capped
0,2264760,347380572101,2958399,2024-04-01 00:54:03.013,Organic,188.1,android,1,188.1
1,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,android,2,660.0
2,2264762,336918719810,1117248,2024-04-01 07:45:51.977,Organic,1000.0,android,1,1000.0
3,2264763,15727668101,142883,2024-04-01 08:10:27.117,Organic,630.0,android,1,630.0
4,2264765,171012023297,2119935,2024-04-01 08:12:47.067,Organic,1286.5,web,1,1286.5
...,...,...,...,...,...,...,...,...,...
1456079,3774837,1078667110922,6185168,2026-03-31 22:59:52.087,Organic,298.0,android,1,298.0
1456080,3774839,973280902501,3003288,2026-03-31 23:08:12.080,Organic,950.0,admin,1,950.0
1456081,3774840,1098348016442,6874883,2026-03-31 23:17:05.110,Organic,420.0,android,2,420.0
1456082,3774841,985498954730,5004168,2026-03-31 23:27:17.847,Organic,1250.0,android,1,1250.0
1456083,3774842,745326602330,168920,2026-03-31 23:29:04.467,Organic,450.0,admin,1,450.0

In [5]:
df_order_level.info()
df_order_level.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1456084 entries, 0 to 1456083
Data columns (total 9 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   OrderId               1456084 non-null  int64
 1   UserId                1456084 non-null  int64
 2   VendorId              1456084 non-null  int64
 3   CreatedDate           1456084 non-null  str
 4   OrderType             1456084 non-null  str
 5   OrderSubTotal         1456084 non-null  float64
 6   Platform              1456084 non-null  str
 7   CityID                1456084 non-null  int64
 8   OrderSubTotal_capped  1456084 non-null  float64
dtypes: float64(2), int64(4), str(3)
memory usage: 148.3 MB

,OrderId,UserId,VendorId,OrderSubTotal,CityID,OrderSubTotal_capped
count,1.456084e+06,1.456084e+06,1.456084e+06,1.456084e+06,1.456084e+06,1.456084e+06
mean,3.015806e+06,3.125571e+11,2.123596e+06,1.222766e+03,1.575137e+00,1.194220e+03
std,4.330907e+05,2.865716e+11,1.706980e+06,2.498508e+04,9.949972e-01,9.167210e+02
min,2.264760e+06,7.226000e+03,3.720000e+03,1.000000e+01,1.000000e+00,1.000000e+01
25%,2.641691e+06,4.253040e+10,5.140880e+05,6.100000e+02,1.000000e+00,6.100000e+02
50%,3.015224e+06,2.536744e+11,1.811715e+06,9.700000e+02,1.000000e+00,9.700000e+02
75%,3.388989e+06,5.031959e+11,3.356223e+06,1.460000e+03,2.000000e+00,1.460000e+03
max,3.774842e+06,1.098348e+12,7.420175e+06,2.930234e+07,6.000000e+00,9.220000e+03

In [6]:
df_order_level["Platform"].value_counts()

Platform
ios        760804
android    627533
web         50705
admin       17042
Name: count, dtype: int64

In [7]:
df_order_level["OrderType"].value_counts()

OrderType
Organic     1401367
Assisted      54717
Name: count, dtype: int64

In [8]:
clean_df = pd.read_csv("feature_data/clean_df.csv")
display(clean_df)

,OrderId,UserId,VendorId,CreatedDate,OrderType,OrderSubTotal,Cuisine,Platform,CityID,OrderSubTotal_capped
0,2264760,347380572101,2958399,2024-04-01 00:54:03.013,Organic,188.1,Multi Cuisine,android,1,188.1
1,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Jalebi,android,2,660.0
2,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Veg & Vegan,android,2,660.0
3,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Indian,android,2,660.0
4,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Vegetarian,android,2,660.0
...,...,...,...,...,...,...,...,...,...,...
4322971,3774840,1098348016442,6874883,2026-03-31 23:17:05.110,Organic,420.0,Biryani,android,2,420.0
4322972,3774841,985498954730,5004168,2026-03-31 23:27:17.847,Organic,1250.0,Italian,android,1,1250.0
4322973,3774841,985498954730,5004168,2026-03-31 23:27:17.847,Organic,1250.0,Pizza,android,1,1250.0
4322974,3774842,745326602330,168920,2026-03-31 23:29:04.467,Organic,450.0,Butter Naan,admin,1,450.0
4322975,3774842,745326602330,168920,2026-03-31 23:29:04.467,Organic,450.0,Indian,admin,1,450.0

In [9]:
clean_df["Platform"].value_counts()

Platform
ios        2221321
android    1893427
web         151911
admin        56317
Name: count, dtype: int64

In [10]:
valid = ["ios", "android", "web", "admin"]

clean_df = clean_df[clean_df["Platform"].isin(valid)]
clean_df["Platform"].value_counts()

Platform
ios        2221321
android    1893427
web         151911
admin        56317
Name: count, dtype: int64

In [11]:
valid = ["ios", "android", "web", "admin"]
df_order_level = df_order_level[df_order_level["Platform"].isin(valid)]
df_order_level["Platform"].value_counts()

Platform
ios        760804
android    627533
web         50705
admin       17042
Name: count, dtype: int64

In [12]:
df_order_level.merge(clean_df, how="left", indicator=True)["_merge"].value_counts()

_merge
both          4322976
left_only           0
right_only          0
Name: count, dtype: int64

In [13]:
clean_df.groupby("Platform").size()

Platform
admin        56317
android    1893427
ios        2221321
web         151911
dtype: int64

In [14]:
df_order_level.groupby("Platform").size()

Platform
admin       17042
android    627533
ios        760804
web         50705
dtype: int64

In [15]:
df_order_level.merge(
    clean_df,
    on=["OrderId"],
    how="left",
    indicator=True,
)["_merge"].value_counts()

_merge
both          4322976
left_only           0
right_only          0
Name: count, dtype: int64

In [16]:
print(clean_df["UserId"].nunique())
print(df_order_level["UserId"].nunique())
print(user_df["UserId"].nunique())

256916
256916
256916

In [17]:
set(clean_df["UserId"]) == set(df_order_level["UserId"])

True

In [18]:
clean_df.groupby("UserId").size().describe()

count    256916.000000
mean         16.826418
std          46.817316
min           1.000000
25%           2.000000
50%           5.000000
75%          13.000000
max        2976.000000
dtype: float64

In [19]:
df_order_level.groupby("UserId").size().describe()

count    256916.000000
mean          5.667549
std          14.876630
min           1.000000
25%           1.000000
50%           2.000000
75%           4.000000
max         776.000000
dtype: float64

In [20]:
merged = df_order_level.merge(
    clean_df,
    on=["OrderId"],
    how="left",
    suffixes=("_order", "_clean"),
)

(merged["UserId_order"] != merged["UserId_clean"]).sum()

np.int64(0)

In [21]:
time_series = pd.read_csv("time_series_new.csv")
display(time_series)

,OrderId,UserId,VendorId,CreatedDate,OrderType,OrderSubTotal,Cuisine,Platform,CityID,OrderSubTotal_capped,date,month,day_of_week,hour,first_order_date,first_month,user_type
0,2264760,347380572101,2958399,2024-04-01 00:54:03.013,Organic,188.1,Multi Cuisine,android,1,188.1,2024-04-01,2024-04,Monday,0,2024-04-01 00:54:03.013,2024-04,New
1,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Jalebi,android,2,660.0,2024-04-01,2024-04,Monday,6,2024-04-01 06:52:46.583,2024-04,New
2,2264762,336918719810,1117248,2024-04-01 07:45:51.977,Organic,1000.0,Cake,android,1,1000.0,2024-04-01,2024-04,Monday,7,2024-04-01 07:45:51.977,2024-04,New
3,2264763,15727668101,142883,2024-04-01 08:10:27.117,Organic,630.0,Bakery,android,1,630.0,2024-04-01,2024-04,Monday,8,2024-04-01 08:10:27.117,2024-04,New
4,2264765,171012023297,2119935,2024-04-01 08:12:47.067,Organic,1286.5,Burger,web,1,1286.5,2024-04-01,2024-04,Monday,8,2024-04-01 08:12:47.067,2024-04,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438994,3774835,199675816202,1674435,2026-03-31 22:59:27.183,Organic,2010.0,Japanese,android,2,2010.0,2026-03-31,2026-03,Tuesday,22,2024-04-13 17:09:56.653,2024-04,Returning
1438995,3774836,1094576288401,6170255,2026-03-31 22:59:34.923,Organic,420.0,Thakali,ios,1,420.0,2026-03-31,2026-03,Tuesday,22,2026-03-29 14:48:13.933,2026-03,New
1438996,3774837,1078667110922,6185168,2026-03-31 22:59:52.087,Organic,298.0,Multi Cuisine,android,1,298.0,2026-03-31,2026-03,Tuesday,22,2026-03-31 16:32:56.827,2026-03,New
1438997,3774840,1098348016442,6874883,2026-03-31 23:17:05.110,Organic,420.0,Biryani,android,2,420.0,2026-03-31,2026-03,Tuesday,23,2026-03-31 23:17:05.110,2026-03,New
1438998,3774841,985498954730,5004168,2026-03-31 23:27:17.847,Organic,1250.0,Italian,android,1,1250.0,2026-03-31,2026-03,Tuesday,23,2026-01-27 15:06:45.430,2026-01,Returning

## Part1: RFM Feature Construction

In [22]:
# recency_days
user_df["last_order_date"] = pd.to_datetime(user_df["last_order_date"]).dt.normalize()
reference_date = pd.Timestamp("2026-03-31")
user_df["recency_days"] = (reference_date - user_df["last_order_date"]).dt.days
display(user_df)

,UserId,total_orders,avg_order_value,total_spend,order_value_std,first_order_date,last_order_date,fav_platform,fav_city,n_platforms_used,n_cities_ordered_from,recency_days,customer_lifespan_days,avg_days_between_orders
0,7226,5,1332.600000,6663.00,590.077368,2024-09-10 19:53:14.763,2025-10-11,ios,3,2,1,171,395,79.000000
1,7397,1,320.000000,320.00,0.000000,2026-02-24 19:06:45.527,2026-02-24,web,1,1,1,35,0,0.000000
2,9802,42,1406.044048,59053.85,636.702285,2024-12-24 09:06:21.120,2026-01-19,ios,1,1,1,71,390,9.285714
3,10817,1,599.000000,599.00,0.000000,2024-06-22 17:16:12.330,2024-06-22,android,1,1,1,647,0,0.000000
4,14885,27,3866.311111,104390.40,1723.575350,2024-04-13 14:20:53.883,2026-03-19,android,1,1,1,12,704,26.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256911,1098287232065,1,500.000000,500.00,0.000000,2026-03-31 22:26:31.887,2026-03-31,ios,5,1,1,0,0,0.000000
256912,1098297712010,1,230.000000,230.00,0.000000,2026-03-31 22:35:59.940,2026-03-31,ios,1,1,1,0,0,0.000000
256913,1098306096002,1,499.000000,499.00,0.000000,2026-03-31 22:44:45.557,2026-03-31,ios,2,1,1,0,0,0.000000
256914,1098324960101,1,1560.000000,1560.00,0.000000,2026-03-31 22:50:58.427,2026-03-31,android,1,1,1,0,0,0.000000
256915,1098348016442,1,420.000000,420.00,0.000000,2026-03-31 23:17:05.110,2026-03-31,android,2,1,1,0,0,0.000000

In [23]:
user_df["recency_days"].describe()

count    256916.000000
mean        249.767006
std         210.609505
min           0.000000
25%          63.000000
50%         197.000000
75%         405.000000
max         729.000000
Name: recency_days, dtype: float64

In [24]:
# different segmentation
one_time = user_df[user_df["total_orders"] == 1]
repeat = user_df[user_df["total_orders"] >= 2]
# distribution
print("=== one-time users ===")
print(one_time["recency_days"].describe())

print("=== repeat users ===")
print(repeat["recency_days"].describe())

=== one-time users ===
count    116883.000000
mean        308.723424
std         215.174399
min           0.000000
25%         116.000000
50%         276.000000
75%         492.000000
max         729.000000
Name: recency_days, dtype: float64
=== repeat users ===
count    140033.000000
mean        200.557154
std         193.420428
min           0.000000
25%          38.000000
50%         132.000000
75%         323.000000
max         729.000000
Name: recency_days, dtype: float64

In [25]:
# a lot zero value effect the distribution
user_df["avg_days_between_orders"].describe()
# using repeat order's to check the distribution again
repeat_users = user_df[user_df["total_orders"] >= 2]
repeat_users["avg_days_between_orders"].describe()

count    140033.000000
mean         39.106876
std          47.030660
min           0.000000
25%           7.500000
50%          23.000000
75%          52.714286
max         362.000000
Name: avg_days_between_orders, dtype: float64

## Retention and Churn Features

### 1-2. K-means segmentation

### 1-3. Derived RFM Scores (Not use this part to do k-means clustering)

## 3. User Behavior Features

In [26]:
display(user_df.head())

,UserId,total_orders,avg_order_value,total_spend,order_value_std,first_order_date,last_order_date,fav_platform,fav_city,n_platforms_used,n_cities_ordered_from,recency_days,customer_lifespan_days,avg_days_between_orders
0,7226,5,1332.600000,6663.00,590.077368,2024-09-10 19:53:14.763,2025-10-11,ios,3,2,1,171,395,79.000000
1,7397,1,320.000000,320.00,0.000000,2026-02-24 19:06:45.527,2026-02-24,web,1,1,1,35,0,0.000000
2,9802,42,1406.044048,59053.85,636.702285,2024-12-24 09:06:21.120,2026-01-19,ios,1,1,1,71,390,9.285714
3,10817,1,599.000000,599.00,0.000000,2024-06-22 17:16:12.330,2024-06-22,android,1,1,1,647,0,0.000000
4,14885,27,3866.311111,104390.40,1723.575350,2024-04-13 14:20:53.883,2026-03-19,android,1,1,1,12,704,26.074074

In [27]:
user_df["fav_platform"].value_counts()

fav_platform
android    125064
ios        119124
web         11260
admin        1468
Name: count, dtype: int64

In [28]:
user_df["n_platforms_used"].value_counts()

n_platforms_used
1    240595
2     15158
3      1082
4        81
Name: count, dtype: int64

In [29]:
# mobile_order_ratio
mobile_orders_df = (
    df_order_level[df_order_level["Platform"].isin(["ios", "android"])]
    .groupby("UserId")["OrderId"]
    .nunique()
    .reset_index(name="mobile_orders")
)
mobile_orders_df
# web_order_ratio
web_orders_df = (
    df_order_level[df_order_level["Platform"] == "web"]
    .groupby("UserId")["OrderId"]
    .nunique()
    .reset_index(name="web_orders")
)
# admin
admin_orders_df = (
    df_order_level[df_order_level["Platform"] == "admin"]
    .groupby("UserId")["OrderId"]
    .nunique()
    .reset_index(name="admin_orders")
)
# total
total_orders_df = (
    df_order_level.groupby("UserId")["OrderId"]
    .nunique()
    .reset_index(name="total_orders")
)
platform_df = (
    total_orders_df.merge(mobile_orders_df, on="UserId", how="left")
    .merge(web_orders_df, on="UserId", how="left")
    .merge(admin_orders_df, on="UserId", how="left")
)
# replace NAN as 0
platform_df[["mobile_orders", "web_orders", "admin_orders"]] = platform_df[
    ["mobile_orders", "web_orders", "admin_orders"]
].fillna(0)
display(platform_df)

               UserId  total_orders  mobile_orders  web_orders  admin_orders
0                7226             5            4.0         0.0           1.0
1                7397             1            0.0         1.0           0.0
2                9802            42           42.0         0.0           0.0
3               10817             1            1.0         0.0           0.0
4               14885            27           27.0         0.0           0.0
...               ...           ...            ...         ...           ...
256911  1098287232065             1            1.0         0.0           0.0
256912  1098297712010             1            1.0         0.0           0.0
256913  1098306096002             1            1.0         0.0           0.0
256914  1098324960101             1            1.0         0.0           0.0
256915  1098348016442             1            1.0         0.0           0.0

[256916 rows x 5 columns]

In [30]:
# platform_df["web_orders"] = platform_df["web_orders"] + platform_df["admin_orders"]

In [31]:
# calculate ratio for different category(web, mobile, admin)
# mobile ratio(ios, android)
platform_df["mobile_order_ratio"] = (
    platform_df["mobile_orders"] / platform_df["total_orders"]
)
# web ratio
platform_df["web_order_ratio"] = platform_df["web_orders"] / platform_df["total_orders"]
# admin ratio
platform_df["admin_order_ratio"] = (
    platform_df["admin_orders"] / platform_df["total_orders"]
)
display(platform_df)

,UserId,total_orders,mobile_orders,web_orders,admin_orders,mobile_order_ratio,web_order_ratio,admin_order_ratio
0,7226,5,4.0,0.0,1.0,0.8,0.0,0.2
1,7397,1,0.0,1.0,0.0,0.0,1.0,0.0
2,9802,42,42.0,0.0,0.0,1.0,0.0,0.0
3,10817,1,1.0,0.0,0.0,1.0,0.0,0.0
4,14885,27,27.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
256911,1098287232065,1,1.0,0.0,0.0,1.0,0.0,0.0
256912,1098297712010,1,1.0,0.0,0.0,1.0,0.0,0.0
256913,1098306096002,1,1.0,0.0,0.0,1.0,0.0,0.0
256914,1098324960101,1,1.0,0.0,0.0,1.0,0.0,0.0
256915,1098348016442,1,1.0,0.0,0.0,1.0,0.0,0.0

In [32]:
# merge platform_df back to user_df
user_df = user_df.merge(
    platform_df[
        ["UserId", "mobile_order_ratio", "web_order_ratio", "admin_order_ratio"]
    ],
    on="UserId",
    how="left",
)
# calculate is_mobile_only
user_df["is_mobile_only"] = (
    (user_df["fav_platform"].isin(["ios", "android"]))
    & (user_df["n_platforms_used"] == 1)
).astype(int)
display(user_df)

,UserId,total_orders,avg_order_value,total_spend,order_value_std,first_order_date,last_order_date,fav_platform,fav_city,n_platforms_used,n_cities_ordered_from,recency_days,customer_lifespan_days,avg_days_between_orders,mobile_order_ratio,web_order_ratio,admin_order_ratio,is_mobile_only
0,7226,5,1332.600000,6663.00,590.077368,2024-09-10 19:53:14.763,2025-10-11,ios,3,2,1,171,395,79.000000,0.8,0.0,0.2,0
1,7397,1,320.000000,320.00,0.000000,2026-02-24 19:06:45.527,2026-02-24,web,1,1,1,35,0,0.000000,0.0,1.0,0.0,0
2,9802,42,1406.044048,59053.85,636.702285,2024-12-24 09:06:21.120,2026-01-19,ios,1,1,1,71,390,9.285714,1.0,0.0,0.0,1
3,10817,1,599.000000,599.00,0.000000,2024-06-22 17:16:12.330,2024-06-22,android,1,1,1,647,0,0.000000,1.0,0.0,0.0,1
4,14885,27,3866.311111,104390.40,1723.575350,2024-04-13 14:20:53.883,2026-03-19,android,1,1,1,12,704,26.074074,1.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256911,1098287232065,1,500.000000,500.00,0.000000,2026-03-31 22:26:31.887,2026-03-31,ios,5,1,1,0,0,0.000000,1.0,0.0,0.0,1
256912,1098297712010,1,230.000000,230.00,0.000000,2026-03-31 22:35:59.940,2026-03-31,ios,1,1,1,0,0,0.000000,1.0,0.0,0.0,1
256913,1098306096002,1,499.000000,499.00,0.000000,2026-03-31 22:44:45.557,2026-03-31,ios,2,1,1,0,0,0.000000,1.0,0.0,0.0,1
256914,1098324960101,1,1560.000000,1560.00,0.000000,2026-03-31 22:50:58.427,2026-03-31,android,1,1,1,0,0,0.000000,1.0,0.0,0.0,1
256915,1098348016442,1,420.000000,420.00,0.000000,2026-03-31 23:17:05.110,2026-03-31,android,2,1,1,0,0,0.000000,1.0,0.0,0.0,1

### 3.2 Geographic Features

In [33]:
user_df["fav_city"].value_counts()

fav_city
1    168940
2     48282
3     17286
4     12114
5      6717
6      3577
Name: count, dtype: int64

In [35]:
# is_city1_primary
user_df["is_city1_primary"] = (user_df["fav_city"] == 1).astype(int)
# is_high_value_city_user (from our eda part we know 1,2 are the highest value)
user_df["is_high_value_city_user"] = (user_df["fav_city"].isin([1, 2])).astype(int)
display(user_df)

,UserId,total_orders,avg_order_value,total_spend,order_value_std,first_order_date,last_order_date,fav_platform,fav_city,n_platforms_used,n_cities_ordered_from,recency_days,customer_lifespan_days,avg_days_between_orders,mobile_order_ratio,web_order_ratio,admin_order_ratio,is_mobile_only,is_city1_primary,is_high_value_city_user
0,7226,5,1332.600000,6663.00,590.077368,2024-09-10 19:53:14.763,2025-10-11,ios,3,2,1,171,395,79.000000,0.8,0.0,0.2,0,0,0
1,7397,1,320.000000,320.00,0.000000,2026-02-24 19:06:45.527,2026-02-24,web,1,1,1,35,0,0.000000,0.0,1.0,0.0,0,1,1
2,9802,42,1406.044048,59053.85,636.702285,2024-12-24 09:06:21.120,2026-01-19,ios,1,1,1,71,390,9.285714,1.0,0.0,0.0,1,1,1
3,10817,1,599.000000,599.00,0.000000,2024-06-22 17:16:12.330,2024-06-22,android,1,1,1,647,0,0.000000,1.0,0.0,0.0,1,1,1
4,14885,27,3866.311111,104390.40,1723.575350,2024-04-13 14:20:53.883,2026-03-19,android,1,1,1,12,704,26.074074,1.0,0.0,0.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256911,1098287232065,1,500.000000,500.00,0.000000,2026-03-31 22:26:31.887,2026-03-31,ios,5,1,1,0,0,0.000000,1.0,0.0,0.0,1,0,0
256912,1098297712010,1,230.000000,230.00,0.000000,2026-03-31 22:35:59.940,2026-03-31,ios,1,1,1,0,0,0.000000,1.0,0.0,0.0,1,1,1
256913,1098306096002,1,499.000000,499.00,0.000000,2026-03-31 22:44:45.557,2026-03-31,ios,2,1,1,0,0,0.000000,1.0,0.0,0.0,1,0,1
256914,1098324960101,1,1560.000000,1560.00,0.000000,2026-03-31 22:50:58.427,2026-03-31,android,1,1,1,0,0,0.000000,1.0,0.0,0.0,1,1,1
256915,1098348016442,1,420.000000,420.00,0.000000,2026-03-31 23:17:05.110,2026-03-31,android,2,1,1,0,0,0.000000,1.0,0.0,0.0,1,0,1

## 4. Cuisine Affinity Features

Cuisine affinity features capture a user’s preference distribution across different cuisine types (e.g., Italian, Chinese, Fast Food). Instead of treating all orders equally, these features quantify what kinds of food a user tends to order, typically as proportions or counts.

The main purpose is to better represent user taste and behavioral patterns, which are not captured by standard metrics like frequency or monetary value. For example, two users may have the same number of orders, but one consistently orders fast food while another prefers premium or niche cuisines—this reflects very different customer profiles.

From a modeling and segmentation perspective, cuisine affinity helps:

- Improve customer segmentation by grouping users with similar preferences
- Enhance recommendation systems by identifying likely cuisine interests
- Support targeted marketing, such as cuisine-specific promotions or partnerships
- Reveal behavioral insights, such as whether certain cuisines are associated with higher spending or retention

In [38]:
df_clean = pd.read_csv("feature_data/clean_df.csv")
display(df_clean)

,OrderId,UserId,VendorId,CreatedDate,OrderType,OrderSubTotal,Cuisine,Platform,CityID,OrderSubTotal_capped
0,2264760,347380572101,2958399,2024-04-01 00:54:03.013,Organic,188.1,Multi Cuisine,android,1,188.1
1,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Jalebi,android,2,660.0
2,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Veg & Vegan,android,2,660.0
3,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Indian,android,2,660.0
4,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Vegetarian,android,2,660.0
...,...,...,...,...,...,...,...,...,...,...
4322971,3774840,1098348016442,6874883,2026-03-31 23:17:05.110,Organic,420.0,Biryani,android,2,420.0
4322972,3774841,985498954730,5004168,2026-03-31 23:27:17.847,Organic,1250.0,Italian,android,1,1250.0
4322973,3774841,985498954730,5004168,2026-03-31 23:27:17.847,Organic,1250.0,Pizza,android,1,1250.0
4322974,3774842,745326602330,168920,2026-03-31 23:29:04.467,Organic,450.0,Butter Naan,admin,1,450.0
4322975,3774842,745326602330,168920,2026-03-31 23:29:04.467,Organic,450.0,Indian,admin,1,450.0

In [40]:
# filtered " multi-cuisine tags " (cause this is meaningless)
df_cuisine = df_clean[df_clean["Cuisine"] != "Multi Cuisine"].copy()
display(df_cuisine)

,OrderId,UserId,VendorId,CreatedDate,OrderType,OrderSubTotal,Cuisine,Platform,CityID,OrderSubTotal_capped
1,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Jalebi,android,2,660.0
2,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Veg & Vegan,android,2,660.0
3,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Indian,android,2,660.0
4,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Vegetarian,android,2,660.0
5,2264761,278589482,1827903,2024-04-01 06:52:46.583,Organic,660.0,Lalmohan,android,2,660.0
...,...,...,...,...,...,...,...,...,...,...
4322971,3774840,1098348016442,6874883,2026-03-31 23:17:05.110,Organic,420.0,Biryani,android,2,420.0
4322972,3774841,985498954730,5004168,2026-03-31 23:27:17.847,Organic,1250.0,Italian,android,1,1250.0
4322973,3774841,985498954730,5004168,2026-03-31 23:27:17.847,Organic,1250.0,Pizza,android,1,1250.0
4322974,3774842,745326602330,168920,2026-03-31 23:29:04.467,Organic,450.0,Butter Naan,admin,1,450.0
4322975,3774842,745326602330,168920,2026-03-31 23:29:04.467,Organic,450.0,Indian,admin,1,450.0

In [ ]:
# Calculate the number of orders per user for each cuisine